CREATE TABLE `demo` (
	`seq` INT(11) NOT NULL AUTO_INCREMENT COMMENT '번호',
	`name` VARCHAR(50) NOT NULL COMMENT '이름',
	`age` INT(11) NULL DEFAULT NULL COMMENT '나이',
	`hobby` VARCHAR(50) NULL DEFAULT NULL COMMENT '취미',
	PRIMARY KEY (`seq`)
);