spring:
  mvc:  
    view: 
      prefix: /WEB-INF/view/
      suffix: .jsp
      
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devluff_cms
    username: devluff
    password: devluff
        
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml